version: "3"

services:

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: npm run start
    links:
      - api
    volumes:
      - ./client:/src/client
      - /src/client/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - "3000:3000"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: npm start
    links:
      - mongo
    volumes:
      - ./api:/src/api
      - /src/api/node_modules
    environment:
      - PORT=3003
    ports:
      - "3003:3003"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: olxparser
    ports:
      - "27017:27017"

  queue:
    build:
      context: .
      dockerfile: Dockerfile.queueManager
    command: npm start
    links:
      - mongo
      - api
      - selenium-hub
    depends_on:
      - selenium-hub
      - chrome
      - mongo
    volumes:
      - ./queueManager:/src/queue
      - /src/queue/node_modules

  selenium-hub:
    image: selenium/hub:3.141.59-xenon
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug:3.141.59-xenon
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - "5900:5900"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: evico2-nginx:dev-${GIT_COMMIT:-latest}
    depends_on:
      - client
      - api
    ports:
      - "80:80"
    logging:
      driver: none





