version: "3"

services:

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: npm run start
    volumes:
      - ./client:/src/client
      - /src/client/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - "3000:3000"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: npm start
    volumes:
      - ./api:/src/api
      - /src/api/node_modules
    environment:
      - PORT=3003
    ports:
      - "3003:3003"

