FROM ubuntu:16.04

RUN apt update && \
    apt install -y curl && \
    curl -sL https://deb.nodesource.com/setup_9.x | bash - && \
    apt install -y nodejs && \
    apt install -y make && \
    apt install -y g++ && \
    apt install unzip libaio1

EXPOSE 3003

WORKDIR /src/api
COPY api/package.json .
RUN npm install
COPY api/src/ /src/api/src


