export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const MENU_CLICK = "MENU_CLICK";

export const GET_IMPORT_REQUESTS = "GET_IMPORT_REQUESTS";
export const GET_IMPORT_REQUEST = "GET_IMPORT_REQUEST";
export const CREATE_IMPORT_REQUEST = "CREATE_IMPORT_REQUEST";
export const UPDATE_IMPORT_REQUEST = "UPDATE_IMPORT_REQUEST";
export const DELETE_IMPORT_REQUEST = "DELETE_IMPORT_REQUEST";
export const UPDATE_IMPORT_REQUEST_STATUS = "UPDATE_IMPORT_REQUEST_STATUS";

export const GET_OFFERS = "GET_OFFERS";
export const GET_OFFER = "GET_OFFER";
export const DELETE_OFFER = "DELETE_OFFER";
export const UPDATE_OFFER = "UPDATE_OFFER";
export const EXPORT_OFFERS = "EXPORT_OFFERS";


export const GET_HEADINGS = "GET_HEADINGS";
export const GET_HEADING = "GET_HEADING";
export const DELETE_HEADING = "DELETE_HEADING";
export const UPDATE_HEADING = "UPDATE_HEADING";
export const CREATE_HEADING = "CREATE_HEADING";
