export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const MENU_CLICK = "MENU_CLICK";

export const GET_IMPORT_REQUESTS = "GET_IMPORT_REQUESTS";
export const GET_IMPORT_REQUEST = "GET_IMPORT_REQUEST";
export const CREATE_IMPORT_REQUEST = "CREATE_IMPORT_REQUEST";
export const UPDATE_IMPORT_REQUEST = "UPDATE_IMPORT_REQUEST";
export const DELETE_IMPORT_REQUEST = "DELETE_IMPORT_REQUEST";
